logging:
  pattern:
    console: '%clr(%gray(%d{yyyy-MM-dd HH:mm:ss.SSS}) - %boldRed(%5p) %blue([%5.20t]) %magenta(%-20.50logger{50}) %yellow(%2M) %green(%2L) : %msg%n)'
  level:
    jrx.anyest.engine.server : debug
    org.springframework.web.servlet.mvc: debug

#spring:
#  datasource:
#    hikari:
#      connection-test-query: SELECT 1
#      connection-timeout: 60000
#      maximum-pool-size: 100
#      max-lifetime: 1200000
#      validation-timeout: 5000
#      idle-timeout: 600000
#      username: root
#      password: 123456
#      jdbc-url: jdbc:mysql://127.0.0.1:3306/mx_local?useSSL=false&characterEncoding=utf8
#      driver-class-name: com.mysql.jdbc.Driver